version: '3.3'
services:
 web:
    image: nginx:latest
    ports:
        - "8888:80"
    volumes:
        - ./test.dev:/var/www       
        - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/logs:/var/log/nginx/
    links:
        - php
 php:
    image: php:7-fpm
    volumes:
        - ./test.dev:/var/www
